npmPublishAccess: public

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: ""

# This is to ensure that yarn.lock files can be updated upon first install
# see https://github.com/goldstack/goldstack/issues/41#issuecomment-1007857278
# Once your project is set up successfully, consider commenting out this option.
enableImmutableInstalls: false

packageExtensions:
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  webpack@*:
    peerDependencies:
      webpack-cli: "*"
    peerDependenciesMeta:
      webpack-cli:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
