npmAuthToken: e629863f-2760-4739-a55b-3a6ae97c958d

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

packageExtensions:
  webpack@*:
    peerDependencies:
      webpack-cli: '*'
    peerDependenciesMeta:
      webpack-cli:
        optional: true
  css@*:
    dependencies:
      fs: '*'




  supertest-session@*:
    dependencies:
      methods: '*'
      cookiejar: '*'

  # sass-loader@*:
  #   dependencies:
  #     node-sass: '*'
  #   peerDependencies:
  #     node-sass: '*'
  # mini-css-extract-plugin@*:
  #   peerDependencies:
  #     webpack: '*'
  #   dependencies:
  #     webpack: '*'
  # extract-css-chunks-webpack-plugin@*:
  #   peerDependencies:
  #     webpack: '*'
  #   dependencies:
  #     webpack: '*'

yarnPath: .yarn/releases/yarn-berry.js
