# npmAuthToken: xxx

npmPublishAccess: public

# npmRegistries:
#  //registry.npmjs.org:
#    npmAuthToken: xxx

packageExtensions:
  css@*:
    dependencies:
      fs: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  supertest-session@*:
    dependencies:
      cookiejar: '*'
      methods: '*'
  webpack@*:
    peerDependencies:
      webpack-cli: '*'
    peerDependenciesMeta:
      webpack-cli:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
