name: Goldstack Monorepo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Build and Test'
    if: "!contains(github.event.head_commit.message, 'ci_skip')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d 
        with:
          fetch-depth: 20
          submodules: recursive
          token: ${{secrets.BUILD_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "public@pureleap.com"
      - run: git config --global user.name "GitHub Actions Build"
      - run: git config --global pull.rebase false
      - run: 'yarn config set --json npmRegistries ''{ "//registry.npmjs.org": { "npmAuthToken": "''"${{secrets.NPM_TOKEN}}"''" } }'''
      - name: Install Yarn
        run: npm install -g yarn@1.22.4
      - name: Install root repo and lint
        run: |
          yarn install
          yarn format
          yarn format:check
          yarn lint:fix

      # Do this for all before library git push messes with history
      - name: Check if libraries changed
        uses: marceloprado/has-changed-path@c0d8dcd816c8972e73782b09e0fab8d255db927b
        id: changed-libs
        with:
          paths: workspaces/templates-lib
      - name: Check if templates changed
        uses: marceloprado/has-changed-path@c0d8dcd816c8972e73782b09e0fab8d255db927b
        id: changed-templates
        with:
          paths: workspaces/templates
      - name: Check if template management changed
        uses: marceloprado/has-changed-path@c0d8dcd816c8972e73782b09e0fab8d255db927b
        id: changed-mgmt
        with:
          paths: workspaces/templates-management
      - name: Check if apps changed
        uses: marceloprado/has-changed-path@c0d8dcd816c8972e73782b09e0fab8d255db927b
        id: changed-apps
        with:
          paths: workspaces/apps
      - name: Check if docs changed
        uses: marceloprado/has-changed-path@c0d8dcd816c8972e73782b09e0fab8d255db927b
        id: changed-docs
        with:
          paths: workspaces/docs

      - name: Build libraries
        run: |
          cd workspaces/templates-lib
          yarn compile
          yarn test:ci
          cd ../..

      - name: Build templates
        run: |
          cd workspaces/templates
          yarn compile
          yarn test:ci
          cd ../..
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Build template management
        run: |
          cd workspaces/templates-management
          yarn compile
          yarn test:ci
          cd ../..

      - name: Build apps
        run: |
          cd workspaces/apps
          yarn compile
          yarn workspace @goldstack/goldstack-api utils:seed-module-templates
          yarn test:ci
          cd ../..
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Build docs
        run: |
          cd workspaces/docs
          yarn compile
          yarn test:ci
          cd ../..
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-

      # Generate schemas and docs
      - name: Generate schemas
        run: |
          yarn generate:schema

      - name: Generate docs
        run: |
          yarn generate:docs

      - name: Publish libraries
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        run: |
          cd workspaces/templates-lib
          yarn version:apply --deferred patch
          yarn version apply --all
          yarn publish
          git status
          git add .
          git status
          git diff-index --quiet HEAD || git commit -m "Releasing new library version"
          git status
          cd ../..
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Push library changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          directory: workspaces/templates-lib
          repository: goldstack/goldstack-lib
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Commit changes to sync submodules
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        run: |
          echo "Commiting for root"
          git status
          git add ./yarn.lock
          git add ./.pnp.js
          git add workspaces/*

          yarn commit Release_new_library_version_ci_skip
          yarn git:fix-detached
          yarn pull

      - name: Push apps changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          directory: workspaces/apps
          repository: goldstack/goldstack-apps
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Push docs changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          directory: workspaces/docs
          repository: goldstack/goldstack-docs
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Push template changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          directory: workspaces/templates
          repository: goldstack/goldstack-templates-priv
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Push template management changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          directory: workspaces/templates-management
          repository: goldstack/goldstack-templates-management
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Fix submodule references
        run: |
          yarn git:fix-detached
          yarn pull

      - name: Push root changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Write current git commit to output
        run: |
          echo "Writing git commit hash to output $(git rev-parse HEAD)"
          git rev-parse HEAD
          echo "::set-output name=patchedcommit::$(git rev-parse HEAD)"

      - name: Build and publish image to DEV
        run: DEBUG=true yarn workspace @goldstack/template-management-cli deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Commit latest deployed image hash
        run: |
          cd workspaces/apps
          git status
          git add packages/template-management-cli/src/state/deployments.json
          git diff-index --quiet HEAD || git commit -m "Publishing updated docker deployment ci_skip"
          git pull
          git status
          cd ../..

      - name: Push deployed image hash change
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{secrets.BUILD_TOKEN}}
          directory: workspaces/apps
          repository: goldstack/goldstack-apps

      - name: Fix submodule references
        run: |
          yarn pull

      - name: Push root changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Write current git commit to output
        run: |
          echo "Writing git commit hash to output $(git rev-parse HEAD)"
          git rev-parse HEAD
          echo "::set-output name=patchedclicommit::$(git rev-parse HEAD)"

      - name: Trigger template build
        run: |
          yarn workspace @goldstack/template-management-cli compile # compile again so that deployment state is updated
          yarn workspace @goldstack/template-management-cli cli schedule-all-deploy-sets --repo goldstack-dev --deployment dev --emailResultsTo mxrogm@gmail.com
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Deploy docs
        run: |
          yarn workspace @goldstack/docs-main deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Deploy API
        run: |
          yarn workspace @goldstack/goldstack-api deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
          # Not actually used, only when infra gets into CI/CD
          STRIPE_API_KEY: ${{secrets.DEV_STRIPE_PRIVATE_KEY}}

      - name: Deploy UI
        run: |
          yarn workspace @goldstack/goldstack-home deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
