name: Goldstack Monorepo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: 'Build and Test'
    if: "!contains(github.event.head_commit.message, 'ci_skip')"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Mega repo
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d
        with:
          fetch-depth: 20
          token: ${{secrets.BUILD_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
      - name: Configure git
        run: |
          git config --global user.email "public@pureleap.com"
          git config --global user.name "GitHub Actions Build"
          git config --global pull.rebase false
      - name: Install Yarn
        run: npm install -g yarn@1.22.4
      - name: Configure yarn
        run: 'yarn config set --json npmRegistries ''{ "//registry.npmjs.org": { "npmAuthToken": "''"${{secrets.NPM_TOKEN}}"''" } }'''
      - name: Install root repo and lint
        run: |
          yarn install
          yarn format
          yarn format:check
          yarn lint:fix

      # Do this for all before library git push messes with history
      - name: Check if libraries changed
        uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-libs
        with:
          paths: .
        env:
          SOURCE: workspaces/templates-lib
      - name: Check if templates changed
        uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-templates
        with:
          paths: .
        env:
          SOURCE: workspaces/templates
      - name: Check if template management changed
        uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-mgmt
        with:
          paths: .
        env:
          SOURCE: workspaces/templates-management
      - name: Check if apps changed
        uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-apps
        with:
          paths: .
        env:
          SOURCE: workspaces/apps
      - name: Check if docs changed
        uses: marceloprado/has-changed-path@8a75b456df5a44a8110dcaa3111c9acc6249ed15
        id: changed-docs
        with:
          paths: .
        env:
          SOURCE: workspaces/docs

      - name: Build libraries
        run: |
          cd workspaces/templates-lib
          yarn compile
          yarn test:ci
          cd ../..

      - name: Build templates
        run: |
          cd workspaces/templates
          yarn compile
          yarn test:ci
          cd ../..
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Build template management
        run: |
          cd workspaces/templates-management
          yarn compile
          yarn test:ci
          cd ../..

      - name: Build apps
        run: |
          cd workspaces/apps
          yarn compile
          yarn workspace @goldstack/goldstack-api utils:seed-module-templates
          yarn test:ci
          cd ../..
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Build docs
        run: |
          cd workspaces/docs
          yarn compile
          yarn test:ci
          cd ../..
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-

      # Generate schemas and docs
      - name: Generate schemas
        run: |
          yarn generate:schema || true

      - name: Generate docs
        run: |
          yarn generate:docs || true

      - name: Publish libraries
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        run: |
          cd workspaces/templates-lib
          yarn version:apply --deferred patch
          yarn version apply --all
          yarn publish
          git status
          git add .
          git status
          git diff-index --quiet HEAD || git commit -m "Releasing new library version (ci_skip)"
          git status
          cd ../..
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          YARN_NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Push changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@65392840bda2e774394d5cd38ca33e5918aec2d3
        with:
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Write current git commit to output
        run: |
          echo "Writing git commit hash to output $(git rev-parse HEAD)"
          git rev-parse HEAD
          echo "::set-output name=patchedcommit::$(git rev-parse HEAD)"

      - name: Build and publish image to DEV
        run: DEBUG=true yarn workspace @goldstack/template-management-cli deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Remove yarn secret
        run: 'yarn config set --json npmRegistries ''{ "//registry.npmjs.org": { "npmAuthToken": "''""''" } }'''

      - name: Commit latest deployed image hash
        run: |
          cd workspaces/apps
          git status
          git add packages/template-management-cli/src/state/deployments.json
          git diff-index --quiet HEAD || git commit -m "Publishing updated docker deployment (ci_skip)"
          git status
          cd ../..
          # include files changed on root
          git add .
          git diff-index --quiet HEAD || git commit -m "GitHub actions build (ci_skip)"
          git status

      - name: Push changes
        if: steps.changed-libs.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@65392840bda2e774394d5cd38ca33e5918aec2d3
        with:
          github_token: ${{secrets.BUILD_TOKEN}}

      - name: Write current git commit to output
        run: |
          echo "Writing git commit hash to output $(git rev-parse HEAD)"
          git rev-parse HEAD
          echo "::set-output name=patchedclicommit::$(git rev-parse HEAD)"

      - name: Trigger template build
        run: |
          yarn workspace @goldstack/template-management-cli compile # compile again so that deployment state is updated
          yarn workspace @goldstack/template-management-cli cli schedule-all-deploy-sets --repo goldstack-dev --deployment dev --emailResultsTo mxrogm@gmail.com
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Deploy docs
        run: |
          yarn workspace @goldstack/docs-main deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Deploy API
        run: |
          yarn workspace @goldstack/goldstack-api deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
          # Not actually used, only when infra gets into CI/CD
          STRIPE_API_KEY: ${{secrets.DEV_STRIPE_PRIVATE_KEY}}

      - name: Deploy UI
        run: |
          yarn workspace @goldstack/goldstack-home deploy dev
        env:
          AWS_USER_NAME: goldstack-dev
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
