# Triggers when running a release in Github
# https://github.com/goldstack/goldstack-mega/releases/new
name: Goldstack Release

on:
  release:
    types: [published]

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: true
          # Checking out the released tag
          ref: ${{ github.event.inputs.github-ref }}
          token: ${{secrets.BUILD_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org
      
      - name: Prepare yarn
        run: |
          npm install -g yarn@1.22.4
      - run: 'yarn config set --json npmRegistries ''{ "//registry.npmjs.org": { "npmAuthToken": "''"${{secrets.NPM_TOKEN}}"''" } }'''
      - name: Install and build
          yarn install
          yarn build
      
      - name: Deploy docs
        run: |
          yarn workspace @goldstack/docs-main deploy prod
        env:
          AWS_USER_NAME: goldstack-prod
          AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
      
      - name: Deploy API
        run: |
          yarn workspace @goldstack/goldstack-api deploy prod
        env:
          AWS_USER_NAME: goldstack-prod
          AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2
      
      - name: Deploy UI
        run: |
          yarn workspace @goldstack/goldstack-home deploy prod
        env:
          AWS_USER_NAME: goldstack-prod
          AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2

      - name: Trigger template build and deploy PROD
        run: |
          yarn workspace @goldstack/template-management-cli compile # compile again so that deployment state is updated
          yarn workspace @goldstack/template-management-cli cli schedule-all-deploy-sets --repo goldstack-prod --deployment prod
        env:
          AWS_USER_NAME: goldstack-prod
          AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-2  
